### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by QwertyIsHere** [MLGSW4G/tfd-autodecrypt#1]
Hi! It's an awesome script we all need, but for me it seems not to be working properly. Is it my resolution (2560x1080) or am I doing something wrong?

**Comment by MLGSW4G** [comment]
I did not mean this script to be used in its current state. In fact, I've only uploaded a version that seems to work stably, at least for me (1920x1080 resolution), although when I tested it, the game couldn't get a RMB click signal. In future, I plan to change the script so that it works at any resolution. As soon as it is fully ready, I will add a readme.txt file to the repository and an executable file to releases.
